config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  resources 'sellers'
  resources :users do
    get 'section'
    get 'listing'
    get 'about'
  end

  get 'index' => 'sellers#index'
  get 'listing' => 'sellers#listing'
  get 'section' => 'sellers#section'
  get 'home' => 'sellers#home'
  get 'about' => 'sellers#about'
  get 'settings' => 'users#settings'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"

  delete 'logout'  => 'sessions#destroy'

  get "/sign-up" => "users#new"

  

end

app/models/seller.rb
class Seller < ActiveRecord::Base

end

app/controllers/sellers_controller.rb
require 'open-uri'
class SellersController < ApplicationController

  def index

    # MY SHOP 

    # query = params.fetch(:query, 'wood')
    
    puts current_user.email
    shop = current_user.email

    # shop = User.find_by_shop_name(params[:shop_name]).shop_name

    # puts params.inspect
    # puts shop.id.to_s + "  " + shop.email

    limit = params[:format]

    api_key = ENV['ETSY_API_KEY']

    url = "https://openapi.etsy.com/v2/shops/#{shop}/listings/active?api_key=#{api_key}&#{limit}&includes=MainImage"
    # byebug
    puts url
    response = JSON.parse(open(url).read)
    @items = response['results']
  

    url = "https://openapi.etsy.com/v2/shops/#{shop}/sections?api_key=#{api_key}&#{limit}&includes=MainImage"
    response3 = JSON.parse(open(url).read)
    @sections = response3['results']

    # defined listing_id (format) in the link_to

    url = "https://openapi.etsy.com/v2/shops/#{shop}/listings/active?api_key=#{api_key}&#{limit}&includes=MainImage"
    response = JSON.parse(open(url).read)
    @page = response['pagination']

        url = "https://openapi.etsy.com/v2/shops/#{shop}?api_key=#{api_key}"
    response4 = JSON.parse(open(url).read)
    @infos = response4['results']

  

    # limit = params[:format]

  end


  def listing

        puts current_user.email
    shop = current_user.email

    id = params[:format]

    api_key = ENV['ETSY_API_KEY']

    url = "https://openapi.etsy.com/v2/listings/#{id}?api_key=#{api_key}"
    # byebug
    response = JSON.parse(open(url).read)
    @items = response['results']

    url = "https://openapi.etsy.com/v2/listings/#{id}/images?api_key=#{api_key}"
    response2 = JSON.parse(open(url).read)
    @images = response2['results']

        url = "https://openapi.etsy.com/v2/shops/#{shop}?api_key=#{api_key}"
    response4 = JSON.parse(open(url).read)
    @infos = response4['results']

  end


  def section

    puts current_user.email
    shop = current_user.email

    section_id = params[:format]

    limit = params[:format]

    api_key = ENV['ETSY_API_KEY']

    url = "https://openapi.etsy.com/v2/shops/#{shop}/sections?api_key=#{api_key}&includes=MainImage"
    response3 = JSON.parse(open(url).read)
    @sections = response3['results']

    url = "https://openapi.etsy.com/v2/shops/#{shop}/sections/#{section_id}/listings/active?api_key=#{api_key}&includes=MainImage"
    response = JSON.parse(open(url).read)
    @items = response['results']

    url = "https://openapi.etsy.com/v2/shops/#{shop}/sections/#{section_id}/listings/active?api_key=#{api_key}&#{limit}&includes=MainImage"
    response = JSON.parse(open(url).read)
    @page = response['pagination']

        url = "https://openapi.etsy.com/v2/shops/#{shop}?api_key=#{api_key}"
    response4 = JSON.parse(open(url).read)
    @infos = response4['results']


  end

  def home 

    puts current_user.email
    shop = current_user.email

  # shop = params.fetch(:shop, 'allencompany')

  api_key = ENV['ETSY_API_KEY']

    url = "https://openapi.etsy.com/v2/shops/#{shop}?api_key=#{api_key}"
    response4 = JSON.parse(open(url).read)
    @infos = response4['results']
  
  end



  def about

    # (policies)

    # shop = params.fetch(:shop, 'allencompany')

    puts current_user.email
    shop = current_user.email

    api_key = ENV['ETSY_API_KEY']

    url = "https://openapi.etsy.com/v2/shops/#{shop}?api_key=#{api_key}"
    response4 = JSON.parse(open(url).read)
    @infos = response4['results']

    # url = "https://openapi.etsy.com/v2/shops/#{shop}/about?api_key=#{api_key}"
    # response5 = JSON.parse(open(url).read)
    # @about = response5['results']

  end


end

app/helpers/seller_helper.rb
module SellerHelper
end

app/views/sellers/about.html.erb
<script>

// $('.mobile-nav-wrap').hide();
$('.js-toggle-menu').click(function(e){
  e.preventDefault();
  $(this).toggleClass('open');
  $('.page-wrap').toggleClass('disabled');
  $('body').toggleClass('disabled');
});
$('.search-menu-toggle').click(function(){
  $(this).toggleClass("on");
  $('.search').slideToggle();
});

 
var feed = new Instafeed({
  clientId: '467ede5a6b9b48ae8e03f4e2582aeeb3',
      get: 'user',
    userId: '6085451',
/*    sortBy: 'most-liked',*/
    limit: 15,
    resolution: 'standard_resolution',
  after: function () {
    var images = $("#instafeed").find('a');
    $.each(images, function(index, image) {
      var delay = (index * 75) + 'ms';
      $(image).css('-webkit-animation-delay', delay);
      $(image).css('-moz-animation-delay', delay);
      $(image).css('-ms-animation-delay', delay);
      $(image).css('-o-animation-delay', delay);
      $(image).css('animation-delay', delay);
      $(image).addClass('animated flipInX');
    });
  },
  template: '<div class="bit-5"><a href="{{link}}" target="_blank"><img src="{{image}}" /><div class="likes">&hearts; {{likes}}</div></a></div>'
});
feed.run();

</script>

<style>

@media (max-width: 30em) {

  #instafeed .likes {
    display:none;
  }
  #instafeed a:hover .likes {
    display:none;
  }

}

/*.ig {
    width:20%;
    height:20%;
    float:left;
}*/

#instafeed a {
  padding:5px 5px 1px 5px;
  margin:10px;
  display:inline-block;
/*  border:1px solid #e1e1e1;
  border-radius: 4px;*/
  position:relative;
}

#instafeed .likes {

  background:rgba(255,255,255,0.3);
  font-family:'futura';
  font-size:.9em;
  position:absolute;
  color:#000000;
  right:5px;
  top:5px;
  left:5px;
  bottom:5px;
  opacity:0;
  text-align:center;
  line-height:200px;
/*  text-shadow:0 1px rgba(0,0,0,0.5);*/
  -webkit-font-smoothing:antialiased;
  -webkit-transition: opacity 100ms ease;
    -moz-transition: opacity 100ms ease;
    -o-transition: opacity 100ms ease;
    -ms-transition: opacity 100ms ease;
    transition: opacity 100ms ease;
}

#instafeed a:hover .likes {
  opacity:1;
}

.abouttitle {
  font-family: "DINComp-Bold", sans-serif;
  font-size:24px;
  text-transform: uppercase;
  font-weight: 100;
  background-color:white; 
  text-align:left; 
  padding:20% 0;
}

.aboutimage {
  background-color:white; 
  padding:6% 0 0 250px;"
}

.instagramname {
  font-family: "DINComp-Bold", sans-serif;
  font-size:14px;
  text-transform: uppercase;
  font-weight: 100;
  background-color:white; 
}

@media (max-width: 30em) {

.aboutimage {
  background-color:white; 
  padding:0 12%;
}

.abouttitle {
text-align: center;
}

.announcement {
  display: none;
}

}

</style>



<div class="frame">
<% @infos.each do |info| %>

    <div class="bit-2">
      <div class="box aboutimage">
      <div style="height:300px; width:300px;"> <%= image_tag info['icon_url_fullxfull'], style: "width:100%; height:100%; border-radius:50%;" %> </div> </hr>
      </div>
    </div>

    <div class="bit-2">
      <div class="box abouttitle">
        <%= info['shop_name'] %> </hr>
        <div class="abouttitle" style="font-size:17px; padding:5% 0;"> <%= info['num_favorers'] %> etsy followers </div>
      </div>
    </div>

<!--     <div class="bit-2">
    <div class="box abouttitle" style="background-color:white; font-size:15px; text-align:left; padding:20% 0;">
          <%= info['num_favorers'] %> etsy followers </hr>
            </div>
</div> -->

        <div class="bit-1">
    <div class="box announcement" style="background-color:white;">
<br>
         <div style="font-size:12px; padding:2% 15%"><%= info['announcement'] %> </div></hr>
           </div>
</div>

<!-- <div class="bit-3">
    <div class="box" style="background-color:white;">
         <h1> sale message </h1><br>
          <%= info['sale_message'] %></hr>
            </div>
</div> -->



<!-- <div class="bit-1">
    <div class="box" style="background-color:white;">
          <h1> shipping policy </h1><br>
          <%= info['policy_shipping'] %> </hr>
            </div>
</div> -->
        
      </div>
    </div>
  <% end %>

      <div class="frame">
      <div style="background-color:white;">

        <div class="bit-1">
            <div class="box this1 instagramname" style="background-color:white;" > 
              instagram -  <%= @current_user.email %></Hr>
                <div id="instafeed"></div>  
            </div>     
          </div>
          
    </div>
</div>

<div class="bit-1">
    <div class="box abouttitle " style="background-color:#efefef; height:200px; font-size:10px;">
      <h1>social bar </h1>
            </div>
</div>

  </div>
</div>
</div>

app/views/sellers/home.html.erb
<script>

$('.js-toggle-menu').click(function(e){
  e.preventDefault();
  $(this).toggleClass('open');
  $('.page-wrap').toggleClass('disabled');
  $('body').toggleClass('disabled');
});


$('.search-menu-toggle').click(function(){
	$(this).toggleClass("on");
	$('.search').slideToggle();
		
});

</script>

app/views/sellers/index.html.erb
<style>

/*.hoveritem:hover+.hoverdiv {
    display: block;
}*/

</style>

<!-- <div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">e</a>
    <ul class="nav">
      <li><%= form_tag('/', method: 'get') do %>
          <%= search_field_tag('shop') %>
          <%= submit_tag('Search') %></li>
    </ul>
  </div>
</div>
<% end %> -->



 <div class="frame">
      <div class="wrapper">
  <div class="sections" style="width:100%;">
    <ul>
    <% @sections.each do |section| %>
      <li><%= link_to section['title'], section_path(format: section["shop_section_id"]) %></li>
    <% end %>
  </div>

 <div class="grid" style="margin:auto;">
       <div class="index-picture grid-item">

        <% @items.each do |item| %>
    <div class="grid-item">
      <div class="listinginfo">
        <ul>
        <%= link_to listing_path(format: item["listing_id"]) do %>
         <li><%= image_tag item["MainImage"]["url_570xN"], :class => "hoveritem" %></li> 
         <% end %>
          <li>$<%= item['price']  %></li>
          <li><%= item['title'] %></li>
          <li><%= link_to 'Show', listing_path(format: item["listing_id"]) %></li>
        </ul>
      </div>
    </div>

      <% end %>
    
  </div>
    </div>

<div class="pages">
    <ul>
    <li><%=link_to @page['effective_page'], sellers_path(format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['effective_offset'].to_s) %></li>
<!--     <li><%=link_to @page['next_page'], sellers_path(format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['next_offset'].to_s) %>  </li>  -->
        <li><span style="font-size:12px"><%=link_to ">", sellers_path(format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['next_offset'].to_s) %></span>  </li> 


  </ul>
</div>


</div>


<script>

// $('.mobile-nav-wrap').hide();
$('.js-toggle-menu').click(function(e){
  e.preventDefault();
  $(this).toggleClass('open');
  $('.page-wrap').toggleClass('disabled');
  $('body').toggleClass('disabled');
});
$('.search-menu-toggle').click(function(){
  $(this).toggleClass("on");
  $('.search').slideToggle();
});

// $('.hoveritem').hover(function() {
//   $( this ).fadeOut( 100 );
//   $( this ).fadeIn( 500 );
// });

var $grid = jQuery('.grid');

$(".grid").imagesLoaded(function(){

  $('.grid').isotope({
    itemSelector: '.grid-item',
    masonry: {
      columnWidth: 310
    }
  });

  $grid.isotope('reloadItems');
});



</script>

app/views/sellers/listing.html.erb
    <style>

    .swiper-container {
        width: 100%;
        height: 100%;
    }

    .swiper-container img {
        max-width: 100%;
        height: 100%;
    }

    .swiper-slide {
        text-align: center;
        font-size: 18px;
        background: #fff;

        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
    }

    .btn {
      width: 250px;
      border:1px black solid;
      height:25px;
      background-color:transparent;
      text-transform: uppercase;
      font-family: 'Fira Sans', sans-serif;
      font-size:12px;
      font-weight: 300;
      margin-top:75px;
      margin-bottom:70px;
    }

    .fave {
      width: 50px;

    }


      .btn:hover {
      border:1px blue solid;

    }

    h2 {
      margin-top:70px;
      margin-bottom:25px;
      font-family: 'Playfair Display', serif;
      font-weight:700;
    }


    </style>

<script>

$('.js-toggle-menu').click(function(e){
  e.preventDefault();
  $(this).toggleClass('open');
  $('.page-wrap').toggleClass('disabled');
  $('body').toggleClass('disabled');
});


$('.search-menu-toggle').click(function(){
  $(this).toggleClass("on");
  $('.search').slideToggle();
    
});


$('.fave').click(function() {
     $('.fave').fadeOut(); 
   });


</script>


<!-- <div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">e</a>
    <ul class="nav">
      <li><%= form_tag('/', method: 'get') do %>
          <%= search_field_tag('id') %>
          <%= submit_tag('Search') %></li>
    </ul>
  </div>
</div>
<% end %> -->
<!-- <div class="row">
  <div class="span12"> -->

<div class="frame">
<div class= "bit-2" style="height:500px;">

    <div class="swiper-container">
        <div class="swiper-wrapper">
          <% @images.each do |image| %>
            <div class="swiper-slide">
              <%= image_tag image['url_570xN'] %>
            </div>
           <% end %> 
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiper-pagination-black"></div>
        <!-- Add Navigation -->
        <div class="swiper-button-prev swiper-button-black"></div>
        <div class="swiper-button-next swiper-button-black"></div>
    </div>
</div>


<div class="side bit-2"> 
  <ul>
    <% @items.each do |item| %>
      <li><h2> <%= item['title'] %></h2></li>
      <li> $<%= item['price']  %></li>

      <li style="font-size:12px;"> <%= item['description'] %></li>

      <span><button class="btn fave"><i class="material-icons" style="font-size:12px;">favorite_border</i></button> <%= button_tag "add to cart  | $" + item['price'], :class => "btn"%> </span>

  <li><%= item['views'] %> views | <%= item['num_favorers'] %> favorites </li>

    <li><a target='_blank' href="<%= item['url'] %>">View Item on Etsy</a></li><br><br>

    <% end %>
  </ul>
</div>

    <!-- jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
    <!-- Swiper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.2.6/js/swiper.jquery.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.2.6/css/swiper.css">

    <!-- Initialize Swiper -->
    <script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev'
    });
    </script>



</div>

app/views/sellers/section.html.erb
<div class="frame">
  <div class="wrapper">
  <div class="sections" style="width:100%;">
    <ul>
    <% @sections.each do |section| %>
      <li><%= link_to section['title'], section_path(format: section["shop_section_id"]) %></li>
    <% end %>
</div>

 <div class="grid">
    <div class="index-picture grid-item">
      <% @items.each do |item| %>
        <div class="grid-item">
          <div class="listinginfo">
        <ul>
        <%= link_to listing_path(format: item["listing_id"]) do %>
         <li><%= image_tag item["MainImage"]["url_570xN"], :class => "hoveritem" %></li> 
         <% end %>
          <li>$<%= item['price']  %></li>
          <li><%= item['title'] %></li>
          <li><%= link_to 'Show', listing_path(format: item["listing_id"]) %></li>
        </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="pages">
    <ul>
    <li><%=link_to @page['effective_page'], section_path(format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['effective_offset'].to_s) %></li>

    <span style="font-size:12px"><%=link_to ">", section_path(format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['next_offset'].to_s) %>  </li> </span>

<!--     <li><%=link_to @page['next_page'], section_path(format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['next_offset'].to_s) %>  </li>  -->
  </ul>
</div>



  <script>

// $('.mobile-nav-wrap').hide();
$('.js-toggle-menu').click(function(e){
  e.preventDefault();
  $(this).toggleClass('open');
  $('.page-wrap').toggleClass('disabled');
  $('body').toggleClass('disabled');
});
$('.search-menu-toggle').click(function(){
  $(this).toggleClass("on");
  $('.search').slideToggle();
});

var $grid = jQuery('.grid');

$(".grid").imagesLoaded(function(){

  $('.grid').isotope({
    itemSelector: '.grid-item',
    masonry: {
      columnWidth: 310
    }
  });

  $grid.isotope('reloadItems');
});

</script>