config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  resources 'sellers'
  resources :users do
    get 'section'
    get 'listing'
    get 'about'
  end

  get 'index' => 'sellers#index'
  get 'listing' => 'sellers#listing'
  get 'section' => 'sellers#section'
  get 'home' => 'sellers#home'
  get 'about' => 'sellers#about'
  get 'settings' => 'users#settings'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"

  delete 'logout'  => 'sessions#destroy'

  get "/sign-up" => "users#new"

  

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :shop_name

	attr_accessor :password
	validates_confirmation_of :password
	before_save :encrypt_password

	def encrypt_password
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end

	def self.authenticate(email, password)

		user = User.where(email: email).first
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end


has_attached_file :image, styles: { small: "64x64>", med: "100x100>", large: "500x500>" }

validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		render "users/new", :layout => false
	end


def create
	@user = User.new(user_params)
	if @user.save
		flash[:notice] = "Welcome to the site!"
		session[:user_id] =  @user.id
		redirect_to "/index"
	else
		flash[:alert] = "There was a problem creating your account. Please try again."
		redirect_to :back
	end
end


def index

  api_key = ENV['ETSY_API_KEY']

	@users = User.all

    allshops =  User.connection.select_values(User.select("email").to_sql)

    # parse?

    puts allshops

    shop = allshops.last

    puts shop

    # each shop do this =

    url = "https://openapi.etsy.com/v2/shops/#{shop}?api_key=#{api_key}"
    response4 = JSON.parse(open(url).read)
    @infos = response4['results']


    puts url


end


def show 

    @user = User.find params[:id]

    puts @user.email

    shop = @user.email

    limit = params[:format]

    api_key = ENV['ETSY_API_KEY']

    url = "https://openapi.etsy.com/v2/shops/#{shop}/listings/active?api_key=#{api_key}&#{limit}&includes=MainImage"
    # byebug
    puts url
    response = JSON.parse(open(url).read)
    @items = response['results']
  

    url = "https://openapi.etsy.com/v2/shops/#{shop}/sections?api_key=#{api_key}&#{limit}&includes=MainImage"
    response3 = JSON.parse(open(url).read)
    @sections = response3['results']

    # defined listing_id (format) in the link_to

    url = "https://openapi.etsy.com/v2/shops/#{shop}/listings/active?api_key=#{api_key}&#{limit}&includes=MainImage"
    response = JSON.parse(open(url).read)
    @page = response['pagination']

    url = "https://openapi.etsy.com/v2/shops/#{shop}?api_key=#{api_key}"
    response4 = JSON.parse(open(url).read)
    @infos = response4['results']

end


 def listing

	# @user = User.find params[:id]

 #    puts @user.email

    # shop = @user.email

    id = params[:format]

    api_key = ENV['ETSY_API_KEY']

    url = "https://openapi.etsy.com/v2/listings/#{id}?api_key=#{api_key}"
    # byebug
    response = JSON.parse(open(url).read)
    @items = response['results']

    url = "https://openapi.etsy.com/v2/listings/#{id}/images?api_key=#{api_key}"
    response2 = JSON.parse(open(url).read)
    @images = response2['results']

    #     url = "https://openapi.etsy.com/v2/shops/#{shop}?api_key=#{api_key}"
    # response4 = JSON.parse(open(url).read)
    # @infos = response4['results']

 end



  def section

@user = User.find params[:user_id]

    puts @user.email

    shop = @user.email

    section_id = params[:format]

    limit = params[:format]

    api_key = ENV['ETSY_API_KEY']

    url = "https://openapi.etsy.com/v2/shops/#{shop}/sections?api_key=#{api_key}&includes=MainImage"
    response3 = JSON.parse(open(url).read)
    @sections = response3['results']

    url = "https://openapi.etsy.com/v2/shops/#{shop}/sections/#{section_id}/listings/active?api_key=#{api_key}&includes=MainImage"
    response = JSON.parse(open(url).read)
    @items = response['results']

    url = "https://openapi.etsy.com/v2/shops/#{shop}/sections/#{section_id}/listings/active?api_key=#{api_key}&#{limit}&includes=MainImage"
    response = JSON.parse(open(url).read)
    @page = response['pagination']

    url = "https://openapi.etsy.com/v2/shops/#{shop}?api_key=#{api_key}"
    response4 = JSON.parse(open(url).read)
    @infos = response4['results']
  end


def about

    # (policies)

    # shop = params.fetch(:shop, 'allencompany')

    @user = User.find params[:user_id]

    puts @user.email

    shop = @user.email

    api_key = ENV['ETSY_API_KEY']

    url = "https://openapi.etsy.com/v2/shops/#{shop}?api_key=#{api_key}"
    response4 = JSON.parse(open(url).read)
    @infos = response4['results']

    # url = "https://openapi.etsy.com/v2/shops/#{shop}/about?api_key=#{api_key}"
    # response5 = JSON.parse(open(url).read)
    # @about = response5['results']
end


    def settings

    end




  def edit
    @user = User.find params[:id]
  end


  # update action
  def update
    @user = User.find params[:id]
        respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end



def destroy
  @user = User.find params[:id]
  @user.destroy
  redirect_to users_path
end



private

def user_params
	params.require(:user).permit(:email, :password, :password_confirmation, :image)
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new.html.erb
<!-- <h1>Sign Up</h1> -->
	<%=form_for User.new do |f| %>
	<%=f.label :shop_name %>
	<%=f.text_field :email, class: 'inpt', placeholder: 'Your shop name' %>
	<%=f.label :password %>
	<%=f.password_field :password, class: 'inpt', placeholder: 'Your password'  %>
	<%=f.label :password_confirmation %>
	<%=f.password_field :password_confirmation,  class: 'inpt', placeholder: 'Your password confirmation'  %>
    <%=f.label :image %>
    <%=f.file_field :image  %>
	<div class="submit-wrap">
	<%=f.submit "Sign Up", class: 'submit'  %>
	</div>
<%end%>



  <script>

  $('.tabs .tab').click(function(){
    if ($(this).hasClass('signin')) {
        $('.tabs .tab').removeClass('active');
        $(this).addClass('active');
        $('.cont').hide();
        $('.signin-cont').show();
    } 
    if ($(this).hasClass('signup')) {
        $('.tabs .tab').removeClass('active');
        $(this).addClass('active');
        $('.cont').hide();
        $('.signup-cont').show();
    }
});
$('.container .bg').mousemove(function(e){
    var amountMovedX = (e.pageX * -1 / 30);
    var amountMovedY = (e.pageY * -1 / 9);
    $(this).css('background-position', amountMovedX + 'px ' + amountMovedY + 'px');
});

  </script>

app/views/users/edit.html.erb
<h1>User Edit</h1>

<ul>
<%= form_for @user, html: { multipart: true }, method: :put do |form| %>
  <li>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </li>

  <li>
    <%= form.label :password %>
    <%= form.text_field :password %>
  </li>
<li>
    <%=form.label :password_confirmation %>
  <%=form.password_field :password_confirmation,  class: 'inpt', placeholder: 'Your password confirmation'  %>
</li>
<li>
    <%= form.label :image %> 
<%= form.file_field :image %> 
</li>

  <%= form.submit :edit %>
<% end %>
</ul>

app/views/users/index.html.erb
<style>

.bg { 
/*	padding:40px 40px; */
	background-color:white;
/*	padding-right:4%;*/
padding-top:30px;
	}

@media (max-width: 40em) {
		.bg { 
			padding-right:3%;
		}
	}

.grid {
  background: #fff;
  max-width: 1400px;
}

/* clear fix */
.grid:after {
  content: '';
  display: block;
  clear: both;
}

/* ---- .grid-item ---- */

.grid-item {
  float: left;
  width: 200px;
  background: #fff;
  border: 2px solid #fff;
  border-color: #fff;
}

.grid-item img {
  max-width:100%;
  max-height:100%;
}

.title {
  font-family: "DINComp-Bold", sans-serif;
  font-size:10px;
  text-transform: uppercase;
  font-weight: 100;
}



</style>


<!-- <div class="frame">
  <div class="wrapper"> -->
	<div class="bg">
		 <div class="grid" style="margin:auto;">
       <div class="index-picture grid-item">

	<% @users.each do |user| %>
	    <div class="grid-item title">
<!-- 	<div class="bit-3">
		<div class="box" style="background-color:white;"> -->
	<%= link_to user.email do %>
		<%= image_tag user.image(:large), :class => "hoveritem" %>
		<% end %>
	<%= link_to user.email, user %>
<!-- 	 <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>  -->
<!-- 	<%= link_to "edit", edit_user_path(user) %> -->
</div>


<!-- 	<% @infos.each do |info| %><br><br> -->
<!-- 	<%= image_tag info['icon_url_fullxfull'], style: "width:100px; height:100px; border-radius:50%;" %> -->
<!-- 	<% end %> -->

<!-- 		</div>
	</div> -->
<% end %>
		</div>
	</div>


	</div>
	</div>
</div> 

<script>

// $('.mobile-nav-wrap').hide();
$('.js-toggle-menu').click(function(e){
  e.preventDefault();
  $(this).toggleClass('open');
  $('.page-wrap').toggleClass('disabled');
  $('body').toggleClass('disabled');
});
$('.search-menu-toggle').click(function(){
  $(this).toggleClass("on");
  $('.search').slideToggle();
});

	$(document).on("scroll", function(){
		if
      ($(document).scrollTop() > 100){
		  $("header").addClass("shrink");
			// updateSliderMargin();
		}
		else
		{
			$("header").removeClass("shrink");
			// updateSliderMargin();
		}
	});

	var $grid = jQuery('.grid');

$(".grid").imagesLoaded(function(){

  $('.grid').isotope({
    itemSelector: '.grid-item',
    masonry: {
      columnWidth: 204
    }
  });

  $grid.isotope('reloadItems');
});

</script>

app/views/users/listing.html.erb
    <style>

    h2 {
      font-size: 30px;
    }

    .price {
      font-size: 30px;
    }

    .swiper-container {
        width: 100%;
        height: 100%;
    }

    .swiper-container img {
        max-width: 100%;
        height: 100%;
    }

    .swiper-slide {
        text-align: center;
        font-size: 18px;
        background: #fff;

        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
    }

    .btn {
      width: 250px;
      border:1px black solid;
      height:25px;
      background-color:transparent;
      text-transform: uppercase;
      font-family: 'Fira Sans', sans-serif;
      font-size:12px;
      font-weight: 300;
      margin-top:75px;
      margin-bottom:70px;
    }

    .fave {
      width: 50px;

    }


      .btn:hover {
      border:1px blue solid;

    }

    h2 {
      margin-top:70px;
      margin-bottom:25px;
      font-family: 'Playfair Display', serif;
      font-weight:700;
    }


    </style>

<script>

$('.js-toggle-menu').click(function(e){
  e.preventDefault();
  $(this).toggleClass('open');
  $('.page-wrap').toggleClass('disabled');
  $('body').toggleClass('disabled');
});


$('.search-menu-toggle').click(function(){
  $(this).toggleClass("on");
  $('.search').slideToggle();
    
});


$('.fave').click(function() {
     $('.fave').fadeOut(); 
   });


</script>


<!-- <div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">e</a>
    <ul class="nav">
      <li><%= form_tag('/', method: 'get') do %>
          <%= search_field_tag('id') %>
          <%= submit_tag('Search') %></li>
    </ul>
  </div>
</div>
<% end %> -->
<!-- <div class="row">
  <div class="span12"> -->

<div class="frame">
<div class= "bit-2" style="height:500px;">

    <div class="swiper-container">
        <div class="swiper-wrapper">
          <% @images.each do |image| %>
            <div class="swiper-slide">
              <%= image_tag image['url_570xN'] %>
            </div>
           <% end %> 
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiper-pagination-black"></div>
        <!-- Add Navigation -->
        <div class="swiper-button-prev swiper-button-black"></div>
        <div class="swiper-button-next swiper-button-black"></div>
    </div>
</div>


<div class="side bit-2"> 
  <ul>
    <% @items.each do |item| %>
      <li><h2> <%= item['title'] %></h2></li>
      <li><div class="price"> $<%= item['price']  %></div></li>

      <li style="font-size:13px;"> <%= item['description'] %></li>

      <span><button class="btn fave"><i class="material-icons" style="font-size:12px;">favorite_border</i></button> <%= button_tag "add to cart  | $" + item['price'], :class => "btn"%> </span>

  <li><%= item['views'] %> views | <%= item['num_favorers'] %> favorites </li>

    <li><a target='_blank' href="<%= item['url'] %>">View Item on Etsy</a></li><br><br>

    <% end %>
  </ul>
</div>

    <!-- jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
    <!-- Swiper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.2.6/js/swiper.jquery.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.2.6/css/swiper.css">

    <!-- Initialize Swiper -->
    <script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev'
    });
    </script>



</div>

app/views/users/page.html.erb
<!-- <h1>User Show</h1>

<div style="float:left; padding-left:50px;">
<strong>Id:</strong> <%= @user.id %><br />
<strong>Email:</strong> <%= @user.email %><br />


<%= link_to "Edit User", edit_user_path(@user) %>
<%= link_to "Delete User", user_path(@user), method: :delete %>
</div>


 -->

 <div class="frame">
      <div class="wrapper">
  <div class="sections" style="width:100%;">
    <ul>

<!-- user section path -->

    <% @sections.each do |section| %>
      <li><%= link_to section['title'], user_section_path(@user, format: section["shop_section_id"]) %></li>
    <% end %>
  </div>

 <div class="grid">
       <div class="index-picture grid-item">

        <% @items.each do |item| %>
    <div class="grid-item">
      <div class="listinginfo">
<!--         <div class="listinginfo bit-4"> -->
        <ul>

        <%= link_to user_listing_path(@user, format: item["listing_id"]) do %>
         <li><%= image_tag item["MainImage"]["url_570xN"], :class => "hoveritem" %></li> 
         <% end %>
          <li>$<%= item['price']  %></li>
          <li><%= item['title'] %></li>
          <li><%= link_to 'Show', listing_path(format: item["listing_id"]) %></li>
        </ul>
      </div>
    </div>

      <% end %>
    
  </div>
    </div>

<div class="pages">
    <ul>
    <li><%=link_to @page['effective_page'], user_sellers_path(@user, format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['effective_offset'].to_s) %></li>
    <li><%=link_to @page['next_page'], user_sellers_path(@user, format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['next_offset'].to_s) %>  </li> 
  </ul>
</div>


</div>



<script>

// $('.mobile-nav-wrap').hide();
$('.js-toggle-menu').click(function(e){
  e.preventDefault();
  $(this).toggleClass('open');
  $('.page-wrap').toggleClass('disabled');
  $('body').toggleClass('disabled');
});
$('.search-menu-toggle').click(function(){
  $(this).toggleClass("on");
  $('.search').slideToggle();
});

var $grid = jQuery('.grid');

$(".grid").imagesLoaded(function(){

  $('.grid').isotope({
    itemSelector: '.grid-item',
    masonry: {
      columnWidth: 310
    }
  });

  $grid.isotope('reloadItems');
});

</script>

app/views/users/section.html.erb
<div class="frame">
  <div class="wrapper">
  <div class="sections" style="width:100%;">
    <ul>
    <% @sections.each do |section| %>
      <li><%= link_to section['title'], user_section_path(@user, format: section["shop_section_id"]) %></li>
    <% end %>
</div>

 <div class="grid">
    <div class="index-picture grid-item">
      <% @items.each do |item| %>
        <div class="grid-item">
          <div class="listinginfo">
        <ul>
        <%= link_to user_listing_path(@user, format: item["listing_id"]) do %>
         <li><%= image_tag item["MainImage"]["url_570xN"], :class => "hoveritem" %></li> 
         <% end %>
          <li>$<%= item['price']  %></li>
          <li><%= item['title'] %></li>
          <li><%= link_to 'Show', listing_path(format: item["listing_id"]) %></li>
        </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="pages">
    <ul>
    <li><%=link_to @page['effective_page'], user_section_path(@user, format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['effective_offset'].to_s) %></li>
    <li><%=link_to @page['next_page'], user_section_path(@user, format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['next_offset'].to_s) %>  </li> 
  </ul>
</div>



  <script>

// $('.mobile-nav-wrap').hide();
$('.js-toggle-menu').click(function(e){
  e.preventDefault();
  $(this).toggleClass('open');
  $('.page-wrap').toggleClass('disabled');
  $('body').toggleClass('disabled');
});
$('.search-menu-toggle').click(function(){
  $(this).toggleClass("on");
  $('.search').slideToggle();
});

var $grid = jQuery('.grid');

$(".grid").imagesLoaded(function(){

  $('.grid').isotope({
    itemSelector: '.grid-item',
    masonry: {
      columnWidth: 310
    }
  });

  $grid.isotope('reloadItems');
});

</script>

app/views/users/settings.html.erb
<style>
.settingsrows {
  font-family: "DINComp-Bold", sans-serif;
  font-size:24px;
  text-transform: uppercase;
}


.rows {
   border-radius: 50%;
   border:3px black solid;
   width:50px;
   height:50px;
   padding: 7px 15px;
   margin-left:30px;
   display:inline-block;
}

.rows:hover {
	background-color:lightgrey;
}

.liststyles {
   width:200px;
   height:200px;
   padding: 7px 15px;
   margin-left:20px;
   display:inline-block;
}

.liststyles:hover {
   border: 3px black solid;
}

.slider {
  height:5px;
  width:340px;
  background-color:lightgrey;
  border-radius: 30px;
  margin-bottom:30px;
}
.scrub {
  position:absolute;
  font-size:42px;
  margin-top:-27px;
  color:#e33;
  padding-left:5px;
  padding-right:5px;
}
.slidecenter {
  position: relative;
  height:5px;
  width:340px;
  left:50%;
  margin-left:-320px;
}
.output {
  color:#000;
  background-color:#fafafa;
  border:0;
  text-align:center;
  font-size:30px;
  width:340px;
  margin-bottom:10px;
  border-radius: 30px;
    border:3px black solid;
}

.settingheight {
	height:160px;
}


  </style>


<div class="frame">
	<div style="background-color:white;">
        <div class="bit-40">
  		<div class="box settingsrows settingheight" style="text-align:right; padding-top:30px; background-color:white;">
  		number of rows
  			</div>
  		</div>
  	
  	<span class="bit-60">
  		<div class="box settingsrows settingheight" style="text-align:left; background-color:white; padding-left: 10px;">
  		<div class="rows">1</div>
  		<div class="rows">2</div>
  		<div class="rows">3</div>
  		<div class="rows">4</div>
  		<div class="rows">5</div>
  	</span>
  	</div>
  	</div>

  	<div class="bit-40">
  		<div class="box settingsrows settingheight" style="text-align:right; padding-top:30px; background-color:white;">
  			font sizes
  		</div>
 	</div>



   <div class="bit-60">
  		<div class="box settingsrows settingheight" style=" background-color:white; text-align:left;">

		 <div class="slidecenter">
		  <div class="slider">
		    <div class="scrub">•</div>
		  </div>
		  <input id="percentage" class="output settingsrows" type="text" value="0">
		</div>

		  			</div>
  		</div>
  	</div>
  </div>



 	<div class="bit-40">
  		<div class="box settingsrows settingheight" style="text-align:right; padding-top:30px; background-color:white;">
  			listing styles
  		</div>
 	</div>



   <div class="bit-60">
  		<div class="box settingsrows settingheight" style=" background-color:white; text-align:left;">
  			<div class="liststyles">
  			<img src="https://56.media.tumblr.com/d0123e85ba653cee67c992bd8217de90/tumblr_o0woz7pltR1simze1o2_400.png"></div>
  			<div class="liststyles">
  			<img src="https://56.media.tumblr.com/6079363699f122d3fb3cf438a31673f2/tumblr_o0woz7pltR1simze1o1_250.png"></div>

		  			</div>
  		</div>
  	</div>
  </div>




</div>


<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/TweenMax.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/utils/Draggable.min.js'></script>



  <script>


Draggable.create(".scrub", {type:"x", edgeResistance:1, bounds:".slider"});
// we are done at this point

// output the value
TweenMax.to(this, 1, {alpha:1, onUpdate:update, repeat:-1});
function update() {
  $('#xpos').val( $('.scrub').position().left + 'px' );
  $('#percentage').val( Math.round( $('.scrub').position().left*1000 / 2720 ) + '%' );
}

</script>

app/views/users/show.html.erb
<!-- <h1>User Show</h1>

<div style="float:left; padding-left:50px;">
<strong>Id:</strong> <%= @user.id %><br />
<strong>Email:</strong> <%= @user.email %><br />


<%= link_to "Edit User", edit_user_path(@user) %>

</div>


 -->

<!--   <% @infos.each do |info| %> 
          <div style="height:75px; width:75px; padding: 5px; top:0; float:left;"> <%= image_tag info['icon_url_fullxfull'], style: "width:100%; height:100%; border-radius:50%;" %> </div>
           <% end %>

<br> -->
 <div class="frame">
      <div class="wrapper">
  <div class="sections" style="width:100%;">
    <ul>

<!-- user section path -->


    <% @sections.each do |section| %>
      <li><%= link_to section['title'], user_section_path(@user, format: section["shop_section_id"]) %></li>
    <% end %>
  </div>

 <div class="grid">
       <div class="index-picture grid-item">

        <% @items.each do |item| %>
    <div class="grid-item">
      <div class="listinginfo">
        <ul>
        <%= link_to user_listing_path(@user, format: item["listing_id"]) do %>
         <li><%= image_tag item["MainImage"]["url_570xN"], :class => "hoveritem" %></li> 
         <% end %>
          <li>$<%= item['price']  %></li>
          <li><%= item['title'] %></li>
          <li><%= link_to 'Show', user_listing_path(@user, format: item["listing_id"]) %></li>
        </ul>
      </div>
    </div>

      <% end %>
    
  </div>
    </div>

<div class="pages">
    <ul>
    <li><%=link_to @page['effective_page'], user_path(@user, format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['effective_offset'].to_s) %></li>
    <li><%=link_to @page['next_page'], user_path(@user, format: "limit=" + @page['effective_limit'].to_s + 
    "&offset=" + @page['next_offset'].to_s) %>  </li> 
  </ul>
</div>


</div>



<script>

// $('.mobile-nav-wrap').hide();
$('.js-toggle-menu').click(function(e){
  e.preventDefault();
  $(this).toggleClass('open');
  $('.page-wrap').toggleClass('disabled');
  $('body').toggleClass('disabled');
});
$('.search-menu-toggle').click(function(){
  $(this).toggleClass("on");
  $('.search').slideToggle();
});

var $grid = jQuery('.grid');

$(".grid").imagesLoaded(function(){

  $('.grid').isotope({
    itemSelector: '.grid-item',
    masonry: {
      columnWidth: 310
    }
  });

  $grid.isotope('reloadItems');
});

</script>