config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  resources 'sellers'
  resources :users do
    get 'section'
    get 'listing'
    get 'about'
  end

  get 'index' => 'sellers#index'
  get 'listing' => 'sellers#listing'
  get 'section' => 'sellers#section'
  get 'home' => 'sellers#home'
  get 'about' => 'sellers#about'
  get 'settings' => 'users#settings'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"

  delete 'logout'  => 'sessions#destroy'

  get "/sign-up" => "users#new"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transfer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!--   Google Icons -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <!-- Swiper -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.2.6/js/swiper.jquery.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.2.6/css/swiper.css">
<!--   Masonry -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.2/isotope.pkgd.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.2.0/imagesloaded.pkgd.min.js"></script>
<!-- Instafeed -->
	<script src="https://cdn.rawgit.com/stevenschobert/instafeed.js/master/instafeed.js"></script>  

  

  <script>

  $('.js-toggle-menu').click(function(e){
    e.preventDefault();
    $(this).toggleClass('open');
    $('.page-wrap').toggleClass('disabled');
    $('body').toggleClass('disabled');
  });
  $('.search-menu-toggle').click(function(){
    $(this).toggleClass("on");
    $('.search').slideToggle();
  });

  </script>
</head>

<body>
<nav class="mobile-nav-wrap" role="navigation">
  <ul class="fixed-mobile-nav">
     <% if current_user %>
    <li><%= link_to 'My Shop', sellers_path %></li>
    <li ><%= link_to 'About', about_path %> </li>
    <li class="js-toggle-menu"><%= link_to 'Blog', home_path %></li>
    <li class="js-toggle-menu"><%= link_to 'Explore', users_path %></li>
      <% else %>
    <p>
    <li><%= link_to 'Explore', users_path %></li>
    <li> <%= link_to "Login", log_in_path %><li>
      <% end %>

  </p>
  </ul>
</nav>

<div class="page-wrap">

  <header>

<span class="left">
    <a class="mobile-menu-toggle js-toggle-menu hamburger-menu" href="#">
      <span class="menu-item"></span>
      <span class="menu-item"></span>
      <span class="menu-item"></span>
   </a>
</span>

   <span class="hello">
    <%= link_to 'Explore', users_path %>
    <%= link_to 'About', about_path %>
             <% if current_user %>
    <%= link_to 'My Shop', sellers_path %>
    <% end %>
  </span>



<img src="https://41.media.tumblr.com/46e1483c161314123fa4852c7524d33f/tumblr_nyqv1c24sn1simze1o1_75sq.png" style="padding: 15px 15px; top:0; float:left;">



<span class="right">
    <a class="search-menu-toggle" href="#">
      <i class="material-icons" style="font-size:50px; padding: 15px 15px; top:0;">search</i>
    </a>
</span>

  </header>  

  <main>

<div class="search hide">
    <div class="wrap">
    <div class="searcher">
        <form id="etsy-search">
      <input type="text" id="etsy-terms" class="searchTerm" placeholder="Search">
      <button type="submit" class="searchButton">
        <i class="material-icons">search</i>
      </button>
      </form>
   </div>
  </div>
</div>

<div style="padding-top:100px; background-color:white;">

  <%= yield %>

  </div>

 <footer> 

  <center>
  <div class="bye">
 <% if current_user %>
 <div style="padding-right:50px; display:inline-block;">
<%= link_to logout_path, method: :delete do %> 
<i class="material-icons">exit_to_app</i>
</div>
<% end %>

<%= link_to settings_path do %> 
<i class="material-icons">settings</i>
<% end %>



<% else %>
  <%= link_to "Log in", log_in_path %>
  <%= link_to "Sign Up", sign_up_path %>
 <% end %></div>

  </center></footer>

  </main>


</body>
</html>

app/views/layouts/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transfer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script>

  $('.tabs .tab').click(function(){
    if ($(this).hasClass('signin')) {
        $('.tabs .tab').removeClass('active');
        $(this).addClass('active');
        $('.cont').hide();
        $('.signin-cont').show();
    } 
    if ($(this).hasClass('signup')) {
        $('.tabs .tab').removeClass('active');
        $(this).addClass('active');
        $('.cont').hide();
        $('.signup-cont').show();
    }
});
$('.container .bg').mousemove(function(e){
    var amountMovedX = (e.pageX * -1 / 30);
    var amountMovedY = (e.pageY * -1 / 9);
    $(this).css('background-position', amountMovedX + 'px ' + amountMovedY + 'px');
});

  </script>

</head>

<body>


    <section class="container">
        <article class="half">
<center><img src="https://40.media.tumblr.com/d90780b12b55614820b974db03ec4448/tumblr_nz7cvdFb8P1simze1o2_500.png" style="width:60px; height:60px;"></center>
              <div class="tabs">
                    <span class="tab signin active"><a href="#signin">Sign in</a></span>
                    <span class="tab signup"><a href="#signup">Sign up</a></span>
              </div>
              <div class="content">
                    <div class="signin-cont cont">

                            <%= yield %>

                    </div>
                    <div class="signup-cont cont">

                          <%= render "users/new" %>
                            <%= yield :users %> 

                    </div>
              </div>
        </article>
        <div class="half bg"></div>
  </section>





 <!-- <footer> 
  <center>
    <div style="margin:150px;">
 <% if current_user %>
    <%= link_to "Log out", logout_path, method: :delete %>
<% else %>
  <%= link_to "Log in", log_in_path %><br>
  <%= link_to "Sign Up", sign_up_path %>
 <% end %>
</div>

  </center></footer> -->



</body>
</html>